-- 함수 연습

SELECT ENAME, UPPER(ENAME), LOWER(ENAME), INITCAP(ENAME)
FROM EMP;

SELECT * FROM EMP
WHERE UPPER(ENAME) LIKE UPPER('%smi%');

SELECT CONCAT(EMPNO, ENAME),
		CONCAT(EMPNO, CONCAT(':', ENAME))
FROM EMP
WHERE ENAME = 'SMITH';

SELECT EMPNO || ENAME,
		EMPNO || ':' || ENAME
FROM EMP e WHERE ENAME = 'SMITH';

SELECT ROUND(1.234)
FROM DEPT d;

SELECT ROUND(1.234)
FROM DUAL;

SELECT * FROM DUAL;

SELECT SYSDATE AS NOW,
SYSDATE - 1 AS YESTERDAY,
SYSDATE + 1 AS TOMORROW
FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'YYYY/MM/DD HH24:MI:SS') AS 현재날짜시간
FROM DUAL;

SELECT * FROM EMP
WHERE HIREDATE = '1981/12/03';

-- 1981년 입사자들 출력

SELECT * FROM EMP
WHERE HIREDATE BETWEEN '1981-01-01' AND '1981-12-31';

SELECT EMPNO, ENAME, SAL, COMM, SAL+COMM,
 	   NVL(COMM, 0),
 	   SAL*12 + NVL (COMM, 0) AS "ANN SAL" -- 컬럼명에 공백을 주고싶다면 큰 따옴표로 묶어주면된다.
FROM EMP
ORDER BY "ANN SAL";