-- 다중행 함수

SELECT ENAME, SUM(SAL) FROM EMP;

SELECT * FROM EMP;

SELECT COUNT(COMM) FROM EMP;

SELECT COUNT(*)  -- 행의 개수를 알려달라, TABLE DATA 개수 출력하기
FROM EMP;

SELECT COUNT(*)
FROM EMP
WHERE DEPTNO = 30;

SELECT COUNT(DISTINCT SAL),
	   COUNT(ALL SAL),
	   COUNT(SAL)
FROM EMP;

SELECT COUNT(COMM)  -- COUNT 함수를 사용하여 추가 수당 열 개수 출력하기
FROM EMP;

SELECT COUNT(*) FROM EMP 
WHERE COMM IS NOT NULL;

-- 최대값과 최소값을 구하는 MAX, MIN 함수

SELECT MAX(SAL) FROM EMP -- 부서 번호가 10번인 사원들의 최대 급여 출력하기
WHERE DEPTNO = 10;

SELECT MIN(SAL) FROM EMP  -- 부서 번호가 10번인 사원들의 최소 급여 출력하기
WHERE DEPTNO = 10;

 SELECT MAX(HIREDATE) -- 부서 번호가 20인 사원의 입사일 중 제일 최근 입사일 출력하기 
 FROM EMP
 WHERE DEPTNO = 20;
 
SELECT MIN(HIREDATE)
FROM EMP
WHERE DEPTNO = 20;

-- 평균값을 구하는 AVG함수

SELECT AVG(SAL) FROM EMP
WHERE DEPTNO = 30;

-- 결과 값을 원하는 열로 묶어 출력하는 GROUP BY

SELECT DEPTNO, AVG(SAL)
FROM EMP
GROUP BY DEPTNO;

SELECT DEPTNO, COUNT(*) --부서별 직원수, POST(그룹명)별 댓글의 수
FROM EMP
GROUP BY DEPTNO;

SELECT DEPTNO, COUNT(*) ECOUNT
FROM EMP
GROUP BY DEPTNO
ORDER BY ECOUNT DESC;

-- 부서 번호 및 직책별, 평균 급여로 정렬하기

SELECT DEPTNO, JOB, AVG(SAL) 
FROM EMP
GROUP BY DEPTNO, JOB
ORDER BY JOB;

SELECT DEPTNO, JOB, COUNT(*)
FROM EMP 
GROUP BY DEPTNO, JOB
ORDER BY JOB;

-- GROUP BY절에 조건을 줄 때 사용하는 HAVING절

-- 각 부서의 직책별 평균 급여를 구하되 그 평균 급여가 2000 이상인 그룹만 출력하기
SELECT DEPTNO, JOB, AVG(SAL)             
FROM EMP e 
GROUP BY DEPTNO , JOB 
HAVING AVG(SAL) >= 2000 -- HAVING 절은 ASAL 못함
ORDER BY DEPTNO, JOB;

-- WHERE 절과 HAVING절의 차이점

SELECT DEPTNO, JOB, AVG(SAL)
FROM EMP
GROUP BY DEPTNO, JOB
HAVING AVG(SAL) > 2000
ORDER BY DEPTNO, JOB;

SELECT DEPTNO, JOB, AVG(SAL)
FROM EMP
WHERE SAL <= 3000
GROUP BY DEPTNO, JOB
HAVING AVG(SAL) > 2000
ORDER BY DEPTNO, JOB;