SELECT * FROM EMP
WHERE DEPTNO = 30
OR  JOB = 'CLERK'
ORDER BY DEPTNO, ENAME;

SELECT * FROM EMP
WHERE SAL > 2000
ORDER BY ENAME;

SELECT * FROM EMP
WHERE ENAME >= 'F';

SELECT * FROM EMP 
WHERE NOT SAL = 3000;

SELECT  * FROM EMP
WHERE DEPTNO = 30
AND JOB = 'SALESMAN';

SELECT * FROM EMP
WHERE JOB = 'MANAGER'
	OR JOB = 'SALESMAN'
	OR JOB = 'CLERK';
	
SELECT  * FROM EMP
WHERE JOB IN ('MANAGER','SALESMAN','CLERK');

SELECT  * FROM  EMP
WHERE JOB NOT IN ('MANAGER','SALESMAN','CLERK');

SELECT * FROM  EMP
WHERE SAL >= 2000 AND SAL <=3000;

SELECT  * FROM  EMP
WHERE SAL BETWEEN 2000 AND 3000;

SELECT  * FROM  EMP
WHERE SAL NOT BETWEEN 2000 AND 3000;

SELECT * FROM EMP
WHERE ENAME NOT LIKE '%AM%';

SELECT  * FROM EMP
WHERE COMM IS  NULL;

SELECT  * FROM EMP
WHERE COMM IS NOT NULL;

SELECT  * FROM EMP
WHERE MGR IS NOT NULL;