-- *로 테이블 전체 열 출력하기
SELECT*FROM EMP;

-- 테이블 부분 열 출력하기

SELECT EMPNO, ENAME, DEPTNO
FROM EMP;

-- EMP 테이블에서 DEPTNO 확인
SELECT DEPTNO
FROM EMP;

-- DISTINCT로 열 중복 제거하기(열이 한개 인 경우)
SELECT DISTINCT DEPTNO
FROM EMP;

-- DISTINCT로 열 중복 제거하기(열이 여러 개인 경우)
SELECT DISTINCT JOB, DEPTNO
FROM EMP;
SELECT ENAME, SAL, SAL*12+COMM
FROM EMP;

-- 별칭을 지정하는 방식
SELECT ENAME, SAL, SAL*12+COMM AS ANNSAL,
COMM FROM EMP;

-- 각각의 열에 내림차순과 올림차순 동시에 사용하기
SELECT*FROM EMP e ORDER BY DEPTNO ASC, SAL DESC;

SELECT * FROM EMP
WHERE DEPTNO = 30
OR  JOB = 'CLERK'
ORDER BY DEPTNO, ENAME;

SELECT * FROM EMP
WHERE SAL > 2000
ORDER BY ENAME;

SELECT * FROM EMP
WHERE ENAME >= 'F';

SELECT * FROM EMP 
WHERE NOT SAL = 3000;

SELECT  * FROM EMP
WHERE DEPTNO = 30
AND JOB = 'SALESMAN';

SELECT * FROM EMP
WHERE JOB = 'MANAGER'
	OR JOB = 'SALESMAN'
	OR JOB = 'CLERK';
	
SELECT  * FROM EMP
WHERE JOB IN ('MANAGER','SALESMAN','CLERK');

SELECT  * FROM  EMP
WHERE JOB NOT IN ('MANAGER','SALESMAN','CLERK');

SELECT * FROM  EMP
WHERE SAL >= 2000 AND SAL <=3000;

SELECT  * FROM  EMP
WHERE SAL BETWEEN 2000 AND 3000;

SELECT  * FROM  EMP
WHERE SAL NOT BETWEEN 2000 AND 3000;

SELECT * FROM EMP
WHERE ENAME NOT LIKE '%AM%';

SELECT  * FROM EMP
WHERE COMM IS  NULL;

SELECT  * FROM EMP
WHERE COMM IS NOT NULL;

SELECT  * FROM EMP
WHERE MGR IS NOT NULL;
